/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    fontFamily: {
      'nunito': ['Nunito'],
    },
    fontSize: {
      xs: ['12px',
        { lineHeight: '140%',
          fontWeight: 'regular & bold' }],
      sm: ['14px',
        { lineHeight: '140%',
          fontWeight: 'regular' }],
      md: ['16px',
        { lineHeight: '140%',
          fontWeight: 'regular' }],
      lg: ['20px',
        { lineHeight: '140%',
          fontWeight: 'regular' }],
      "heading-xs": ['14px',
        { lineHeight: '140%',
          fontWeight: '700' }],
      "heading-sm": ['16px',
        { lineHeight: '140%',
          fontWeight: '700' }],
      "heading-md": ['20px',
        { lineHeight: '140%',
          fontWeight: '700' }],
      "heading-lg": ['32px',
        { lineHeight: '140%',
          fontWeight: '700' }],
      'heading-xl': ['48px',
        { lineHeight: '140%',
          fontWeight: '800' }],
      'heading-hg': ['96px', {
        lineHeight: '100%',
        fontWeight: '800' }],
    },
    extend: {
      colors: {
        'blue-light': '#8FB2F5',
        'gray-900': '#13131A',
        'gray-800': '#16161F',
        'gray-700': '#1C1C27',
        'gray-600': '#222224',
        'gray-500': '#3B3B54',
        'gray-400': '#7F7F98',
        'gray-300': '#ABABC4',
        'gray-200': '#BFBFD4',
        'gray-100': '#FAFAFA',
        'white': '#FFFFFF',
      },
    },
  },

  plugins: [],
}