/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    fontFamily: {
      'nunito': ['Nunito'],
    },
    fontSize: {
      xs: ['12px',
        { lineHeight: '140%',
          fontWeight: 'regular & bold' }],
      sm: ['14px',
        { lineHeight: '140%',
          fontWeight: 'regular' }],
      md: ['16px',
        { lineHeight: '140%',
          fontWeight: 'regular' }],
      lg: ['20px',
        { lineHeight: '140%',
          fontWeight: 'regular' }],
      xl: ['14px',
        { lineHeight: '140%',
          fontWeight: 'bold' }],
      "2xl": ['16px',
        { lineHeight: '140%',
          fontWeight: 'bold' }],
      "3xl": ['20px',
        { lineHeight: '140%',
          fontWeight: 'bold' }],
      "4xl": ['32px',
        { lineHeight: '140%',
          fontWeight: 'bold' }],
      '5xl': ['48px',
        { lineHeight: '140%',
          fontWeight: 'bold' }],
      '6xl': ['96px', {
        lineHeight: '100%',
        fontWeight: 'ExtraBold' }],
    },
  },
    extend: {},
  plugins: [],
}